import { Footer } from "@/components/marketing/footer";
import Navbar from "@/components/marketing/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Accommodations System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen py-20 px-10">
      <Navbar />
      {children}
      <Footer />
    </main>
  );
}
